name: "lancer-server"

services:
  # Original Avalanche Service
  avalanche:
    build:
      context: subnet-evm
      dockerfile: ../Dockerfile
      args:
        AVALANCHE_VERSION: latest  # Update with the appropriate version
    ports:
      - "9650:9650"  # Bind container port 9650 to host IP 173.249.4.90
      - "9671:9671"  # Bind container port 9671 to host IP 173.249.4.90
    volumes:
      - ./avalanche:/avalanche
    command: >
      /avalanchego/build/avalanchego
      --data-dir=/avalanche
      --network-id=fuji
      --config-file=/avalanche/configs/node.json
      --staking-port=9671
    restart: unless-stopped

  # New Bvalanche Service
  bvalanche:
    build:
      context: subnet-evm
      dockerfile: ../Dockerfile
      args:
        AVALANCHE_VERSION: latest  # Update with the appropriate version
    ports:
      - "9652:9650"  # Bind container port 9650 to host IP 173.212.245.59
      - "9651:9651"  # Bind container port 9651 to host IP 173.212.245.59
    volumes:
      - ./bvalanche:/avalanche
    command: >
      /avalanchego/build/avalanchego
      --data-dir=/avalanche
      --network-id=fuji
      --config-file=/avalanche/configs/node.json
    restart: unless-stopped

  # Service for the Watchdog
  watchdog:
    build:
      context: .
      dockerfile: Dockerfile.watchdog
    volumes:
      - ./avalanche:/avalanche
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped

  # Service for Health Checks
  health:
    build:
      context: .
      dockerfile: Dockerfile.health
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "8000:8000"
    restart: unless-stopped

  # Proxy Service
  proxy:
    image: caddy:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped


volumes:
  caddy_data:
