name: "lancer-server"

services:
  # Service for the first Dockerfile
  avalanche:
    build:
      context: subnet-evm
      dockerfile: ../Dockerfile
      args:
        AVALANCHE_VERSION: latest # Update with the appropriate version
    ports:
      - "127.0.0.1:9650:9650"
      - "9651:9651"
    volumes:
      - ./avalanche:/avalanche
    command: /avalanchego/build/avalanchego --data-dir=/avalanche --network-id=fuji --config-file=/avalanche/configs/node.json

  # Service for the watchdog
  watchdog:
    build:
      context: .
      dockerfile: Dockerfile.watchdog
    volumes:
      - ./avalanche:/avalanche
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

networks:
  default:
    driver: bridge
